- hosts: all
  become: true
  vars:
    user: user
  tasks:
    - name: Creates rvm directory
      ansible.builtin.file:
        path: /home/{{user}}/rvm
        state: directory
        owner: "{{user}}"
        group: "{{user}}"

    - name: Copying archive
      copy:
        src: data
        dest: /home/{{user}}
        owner: "{{user}}"
        group: "{{user}}"
        mode: '0775'

    - name: Unarchive rvm
      unarchive:
        src: /home/{{user}}/data/rvm-stable.tar.gz
        dest: /home/{{user}}/rvm
        remote_src: yes
        owner: "{{user}}"
        group: "{{user}}"
        list_files: yes
      register: archive_contents

    - name: Install dependencies
      apt:
        pkg:      
          - g++
          - gcc
          - autoconf
          - automake
          - bison
          - libc6-dev
          - libffi-dev
          - libgdbm-dev
          - libncurses5-dev
          - libsqlite3-dev
          - libtool
          - libyaml-dev
          - make
          - pkg-config
          - sqlite3
          - zlib1g-dev
          - libgmp-dev
          - libreadline-dev
        state: latest
        update_cache: true

    - name: Install rvm (and libssl)
      shell:
        cmd: export ARC=/home/{{user}}/rvm/{{ archive_contents.files[0].split('/')[0] }} &&  chmod +x /home/{{user}}/data/install-rvm.sh  && /home/{{user}}/data/install-rvm.sh 2&> /dev/null

    - name: Copying modules
      copy:
        src: /home/{{user}}/data/{{ item }}
        dest: /srv/rvm/archives/
        remote_src: yes
        owner: root
        group: rvm
        mode: '0644'
      with_items:
        - "rubygems-2.4.8.tgz"
        - "ruby-2.0.0-p576.tar.bz2"
        - "yaml-0.1.6.tar.gz"

    - name: Appending the group 'rvm' to the user's groups
      user:
        name: "{{user}}"
        groups: rvm
        append: yes

    - name: Install ruby
      become: true 
      shell: chmod +x /home/{{user}}/data/install-ruby.sh  && /home/{{user}}/data/install-ruby.sh

    - name: Reset ssh connection to allow user changes to affect 'current login user'
      meta: reset_connection

    - name: Set default version
      become: no 
      shell: 'bash -lc "source /etc/profile.d/rvm.sh  && rvm use 2.0.0-p576 --default"'

    - name: Clear temporary files
      file: 
        path={{ item }}
        state=absent
      with_items:
        - "/home/{{user}}/data"
        - "/home/{{user}}/rvm"